name: Bats tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Setup Bats testing framework
      uses: mig4/setup-bats@v1.2.0
    - name: Run bats tests
      run: bats test/*.bats
